DROP DATABASE IF EXISTS BankDBTest;
CREATE DATABASE BankDBTest;

CREATE TABLE IF NOT EXISTS `BankDBTest`.`Users` (
 `Id` INT NOT NULL AUTO_INCREMENT,
 `Login` VARCHAR(30) NOT NULL,
 `Password` VARCHAR(30) NOT NULL,
 `Passport` VARCHAR(30) NOT NULL,
 PRIMARY KEY (`Id`));

CREATE TABLE IF NOT EXISTS `BankDBTest`.`Accounts` (
 `Id` INT NOT NULL AUTO_INCREMENT,
 `UserId` INT NOT NULL,
 'Balance' DECIMAL(20,5),
 PRIMARY KEY (`Id`));